### ISSUE TITLE
failed to resolve type info of `@solid-primitives/storage`

### ISSUE THREAD

**Issue by Reverier-Xu** [solidjs-community/solid-primitives#639]
### Describe the bug

after upgrading to 3.6.0, I got this:

```
✘ [ERROR] Failed to resolve entry for package "@solid-primitives/storage". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///./web/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:49442:17)
    at resolvePackageEntry (file:///./web/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:49439:5)
    at tryNodeResolve (file:///./web/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/no
... and 81 lines more
```

the file structures has changed from `3.5.0`, `dist/index.d.ts` -> `dist/index/index.d.ts`.

### Minimal Reproduction Link

N/A

**Comment by hawkerboy7** [comment]
I have the exact same problem as well

**Comment by atk** [comment]
I just merged a fix, give me a few minutes to release it.

**Comment by atk** [comment]
Release job failed due to CI constraints. Have to run it again.

**Comment by atk** [comment]
OK, 3.7.0 is available.
